Updated for msal 1.0.0
sunilbandla/vue-msal-sample pull request #5
Opened 2019-07-30 02:40 UTC by workeffortwaste

2019-07-30 14:29 UTC, workeffortwaste commented
If you wanted to continue to use the live example you would need to re-add your own credentials.

2019-09-08 11:37 UTC, sunilbandla requested changes
Sorry about the late response. Thanks for the PR!

2019-09-08 11:37 UTC, sunilbandla commented on src/services/auth.service.js
> +            return this.app.getAccount();
Can you please fix the formatting here?

2019-09-08 11:37 UTC, sunilbandla commented on src/App.vue
> +    if(account){
Can you please add space after `if`?

2019-09-08 11:37 UTC, sunilbandla commented on src/services/auth.service.js
> -    if (window.location.hostname !== '127.0.0.1') {
Does it work on localhost without this check?

2021-11-22 15:47 UTC, closed without merging